In [2]:
import tensorflow as tf 
import numpy as np
print("TensorFlow version:", tf.__version__ )

TensorFlow version: 2.4.1


In [3]:
print ("Eager execution is:", tf. executing_eagerly ())

Eager execution is: True


# Tensor
TensorFlow中的 "Tensor", 表示张量，其实就是**多维数组**。
- Python中的列表Iist
- NumPy中的数组对象ndarray

<img src="https://i.loli.net/2021/03/18/pbTBmeiUIhvwKYW.png" alt="image-20210317184050936" style="zoom: 50%;" />

### 创建Tensor对象

张量由Tensor类实现，每个张量都是一个Tensor对象

- tf.constant()函数:
  创建张量

  ```python
  tf.constant(value, dtype, shape)
  ```

  - value : 数字/Python列表/NumPy数组
  - dtype: 元素的数据类型 
  - shape: 张量的形状

In [5]:
tf. constant ([[1,2],[3,4]])

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [34]:
a = tf.constant([2,3])
print(a.dtype,a.shape,a.ndim,sep='\n')
print(tf.rank(a))

<dtype: 'int32'>
(2,)
1
tf.Tensor(1, shape=(), dtype=int32)


### 张量元素的数据类型

<img src="https://i.loli.net/2021/03/18/DEvSN84wPe6lTgL.png" alt="image-20210317184944334" style="zoom:50%;" />



### `tf.cast()`: 改变张量中元素的数据类型

```python
tf.cast (x, dtype)
```



In [7]:
# example
a = tf.constant(np.array([1.,2.]))
print(a.dtype)

b = tf.cast(a,dtype=tf.float32)
print(b.dtype)

<dtype: 'float64'>
<dtype: 'float32'>


 
### 创建全0/1张量

```python
# all-0 tensor
tf.zeros( shape, dtype = tf.float32)

# all-1 tensor
tf.ones( shape, dtype= tf.float32)
```



In [8]:
tf.zeros((6))

<tf.Tensor: shape=(6,), dtype=float32, numpy=array([0., 0., 0., 0., 0., 0.], dtype=float32)>

In [9]:
tf.ones((2,1))

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[1.],
       [1.]], dtype=float32)>

### 创建元素值都相同的张量—— `tf.fill()`函数

```python
tf.fill( dims, value )
```



In [11]:
tf. fill([2,3], 9)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[9, 9, 9],
       [9, 9, 9]], dtype=int32)>

### 创建随机数张量一一正态分布

```python
tf.random.normal( shape, mean=0, stddev=1, dtype)
```



In [12]:
tf. random. normal ([2,2])

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1.4484229 , 1.3438134 ],
       [0.53851694, 0.39199248]], dtype=float32)>

### 创建随机数张量一截断正态分布

```python
tf.random.truncated normal( shape, mean, stddev, dtype)
```
- 返回一个截断的正态分布 
- 截断的标准是2倍的标准差

例如，当均值为0，标准差为1时
- 使用tf.truncated_normal()，不可能出现区间[-2,2]以外的点
- 使用tf.random_normal()，可能出现[-2,2]以外的点

### 设置随机种子一一tf.random.set_seed()函数

In [14]:
tf.random.set_seed(8)
tf.random.normal((2,2))

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 1.2074401, -0.7452462],
       [ 0.6908678, -0.7635988]], dtype=float32)>

In [15]:
tf.random.set_seed(8)
tf.random.normal((2,2))

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 1.2074401, -0.7452462],
       [ 0.6908678, -0.7635988]], dtype=float32)>

In [16]:
tf.random.set_seed(9)
tf.random.normal((2,2))

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-1.2324815 ,  0.06311513],
       [ 0.8433409 , -0.05603401]], dtype=float32)>

### 创建均匀分布张量一一tf.random.uniform()函数

```python
tf.random.uniform(shape,minval, maxval, dtype)
```

- 前闭后开



In [18]:
tf. random. uniform (shape =(3,3), minval =0, maxval =10, dtype = tf.int32)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[5, 6, 9],
       [6, 4, 8],
       [1, 2, 1]], dtype=int32)>

### 洗牌函数：`tf.random.shuffle()`函数

- 沿着**第一维**打乱


In [20]:
a = tf.constant([[1,2],[3,4],[5,6]])
tf.random.shuffle(a)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6],
       [1, 2]], dtype=int32)>

In [21]:
y = [1,2,3,4,5,6]
tf.random.shuffle(y)

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([1, 3, 4, 2, 6, 5], dtype=int32)>

In [22]:
z = np.arange(5)
tf.random.shuffle(z)

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([1, 4, 2, 3, 0])>

### 创建序列一一`tf.range()`函数

```python
tf.range(start=0, limit, delta=1, dtype)
```

- 前闭后开



In [23]:
tf. range (10)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [26]:
tf. range (10,delta=2)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 2, 4, 6, 8], dtype=int32)>

In [27]:
tf. range (1,10,delta=2)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 3, 5, 7, 9], dtype=int32)>