### 改变张量的形状

```python
tf.reshape(tensor,shape)
```



In [1]:
import numpy as np
import tensorflow as tf
tf. constant (np. arange (24). reshape (2, 3, 4))

<tf.Tensor: shape=(2, 3, 4), dtype=int64, numpy=
array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])>

### 增加维度

```python
tf.expand_dims(input,axis)
```

增加的这个维度上，**长度为1**



In [4]:
t= tf. constant ([1,2])
print (t. shape)

(2,)


In [3]:
t =tf. expand_dims(t,1)
print (t. shape)

(2, 1)


### 删除维度：只能删除长度为 1 的维度

```python
tf.squeeze( input, axis)
```

In [8]:
t = tf.ones((1,2,1,3,1))
print(t)

tf.Tensor(
[[[[[1.]
    [1.]
    [1.]]]


  [[[1.]
    [1.]
    [1.]]]]], shape=(1, 2, 1, 3, 1), dtype=float32)


In [9]:
t1 = tf.ones((1,2,1,3,1))
tf.shape(tf.squeeze(t1))

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 3], dtype=int32)>

In [10]:
t2 = tf.ones((1,2,1,3,1))
tf.shape(tf.squeeze(t2,[2,4]))

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

### 交换维度

```python
tf.transpose(a, perm )
```
交换维度，不仅改变了张量的视图, 同时也改变了张量的存储顺序


In [11]:
x= tf. constant ([[1,2,3],[4,5,6]])
x


<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [12]:
tf. transpose (x, perm =[1,0])

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)>

### 拼接张量

```python
tf.concat( tensors, axis)
```


In [13]:
t1 = [[1,2,3],[4,5,6]]
t2 = [[7,8,9],[3,2,1]]

In [15]:
tf.concat([t1,t2],0)

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [3, 2, 1]], dtype=int32)>

### 分割张量：将一个张量拆分成多个张量, 分割后维度不变

```python
tf.split( value, num_or_size_splits, axis=0)
```

- `num_or_size_splits`
    - 2：分割成2个张量 
    - [1,2,1]：就表示分割成三个张量, 长度分别是1,2,1

In [17]:
x = tf.range(24)
x = tf.reshape(x,(4,6))
x

<tf.Tensor: shape=(4, 6), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]], dtype=int32)>

In [18]:
tf.split(x,(2,4),1)

[<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
 array([[ 0,  1],
        [ 6,  7],
        [12, 13],
        [18, 19]], dtype=int32)>,
 <tf.Tensor: shape=(4, 4), dtype=int32, numpy=
 array([[ 2,  3,  4,  5],
        [ 8,  9, 10, 11],
        [14, 15, 16, 17],
        [20, 21, 22, 23]], dtype=int32)>]

### 堆叠张量

```python
tf.stack( values, axis)
```

合并张量时，创建一个新的维度



In [19]:
x = tf.constant([1,2,3])
y = tf.constant([4,5,6])

In [20]:
tf.stack([x,y],0)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [21]:
tf.stack([x,y],1)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)>

### 分解张量

- 将张量分解为多个张量
- 分解后得到的每个张量, 和原来的张量相比，维数都少了一维

```python
tf.unstack( values, axis)
```

In [23]:
a = tf.constant([[1,2,3],[4,5,6]])
a

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [25]:
tf.unstack(a,axis=0)

[<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([4, 5, 6], dtype=int32)>]

In [26]:
tf.unstack(a,axis=1)

[<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 4], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 5], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 6], dtype=int32)>]